# wrangler.toml
name = "ai-daily"
main = "src/index.js" # <-- Important: path to your main worker script
compatibility_date = "2025-05-20" # Or your project's compatibility date
workers_dev = true

kv_namespaces = [
  { binding = "DATA_KV", id = "4cacd7ba71aa4c4c92447012c28345af" }
]

[vars]
IMG_PROXY = ""  #图片代理链接，用于处理图片不显示
OPEN_TRANSLATE = "true"
USE_MODEL_PLATFORM = "OPEN" #GEMINI, OPEN
# GEMINI_API_KEY 在环境变量中设置
GEMINI_API_URL = "https://api-proxy.me/gemini" #网上公共的代理api
DEFAULT_GEMINI_MODEL = "gemini-3-pro-preview"
# OPENAI_API_KEY 在环境变量中设置
OPENAI_API_URL = "https://api.deepseek.com" # Or your OpenAI compatible API URL
DEFAULT_OPEN_MODEL = "deepseek-chat"
FOLO_COOKIE_KV_KEY = "folo_auth_cookie" 
FOLO_DATA_API = "https://api.follow.is/entries"
FOLO_FILTER_DAYS = 3
AIBASE_FEED_ID = "69533603812632576" 
AIBASE_FETCH_PAGES = "3" 
XIAOHU_FEED_ID = "151846580097413120" 
XIAOHU_FETCH_PAGES = "2" 
HGPAPERS_FEED_ID = "41359648680482832" 
HGPAPERS_FETCH_PAGES = "2" 
JIQIZHIXIN_FEED_ID = "41459996870678583" 
JIQIZHIXIN_FETCH_PAGES = "1" 
QBIT_FEED_ID = "58864180026527744" 
QBIT_FETCH_PAGES = "1" 
XINZHIYUAN_FEED_ID = "60901577013168128" 
XINZHIYUAN_FETCH_PAGES = "1" 
TWITTER_LIST_ID = "58126965514597376" 
TWITTER_FETCH_PAGES = "3" 
REDDIT_LIST_ID = "167576006499975168" 
REDDIT_FETCH_PAGES = "2" 
PROJECTS_API_URL = "https://git-trending.justlikemaki.vip/topone/?since=daily"
# GITHUB_TOKEN 在环境变量中设置
GITHUB_REPO_OWNER = "DylanDDeng"  # 请替换为你的 GitHub 用户名
GITHUB_REPO_NAME = "ai-bubblebrain-daily-news"  # 请替换为你的仓库名
GITHUB_BRANCH = "main"
LOGIN_USERNAME = "root"
LOGIN_PASSWORD = "toor"
DAILY_TITLE = "AI资讯"
DAILY_TITLE_MIN = " `AI 日报` "
PODCAST_TITLE = "来生小酒馆"
PODCAST_BEGIN = "嘿，亲爱的V，欢迎收听新一期的来生情报站，我是你们的老朋友，何夕2077"
PODCAST_END = "今天的情报就到这里，注意隐蔽，赶紧撤离"
BOOK_LINK = ""
INSERT_FOOT = "false"
INSERT_APP_URL = "<h3>[查看完整版AI日报↗️ https://ai.hubtoday.app/](https://ai.hubtoday.app/)</h3>"